// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8mLJKD7HN222kbQJH2wRLABxDsaFmpEk',
    appId: '1:672830071766:android:1e691485f567de8ef3ba77',
    messagingSenderId: '672830071766',
    projectId: 'kelime-fatihi-cd8ca',
    storageBucket: 'kelime-fatihi-cd8ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ4b7PKZG5EgzZZsqjN3p21pGAveYC_ek',
    appId: '1:672830071766:ios:688fa7a5c4fca593f3ba77',
    messagingSenderId: '672830071766',
    projectId: 'kelime-fatihi-cd8ca',
    storageBucket: 'kelime-fatihi-cd8ca.firebasestorage.app',
    iosClientId: '672830071766-s7ruut99678sn62cctgeb9k1jg2qbete.apps.googleusercontent.com',
    iosBundleId: 'com.esalde.kelimefatihi',
  );
}
